version: '3'
  
services:
  activemq:
    image: "webcenter/activemq:5.14.3"
    volumes:
      - $PWD/mydata/activemq:/data/activemq
      - $PWD/log:/var/log/activemq
    ports:
      - "61616:61616"
      - "8161:8161"
