version: '3'

services:
  single-node-es:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.1
    container_name: single-node-es
    environment:
      discovery.type: single-node
    volumes: 
      - $PWD/data:/usr/share/elasticsearch/data
    ports: 
      - 9200:9200
      - 9300:9300
